dataset:
  train_dir: ../Offroad_Segmentation_Training_Dataset/train
  val_dir: ../Offroad_Segmentation_Training_Dataset/val
  test_dir: ../Offroad_Segmentation_testImages

training:
  batch_size: 2
  epochs: 30
  learning_rate: 0.0001

model:
  backbone: dinov2_vits14
  num_classes: 10

output:
  save_dir: outputs
